# Generated by Django 6.0.5 on 2026-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("ph", "Philippines"),
                            ("academic", "Academic"),
                            ("ent", "Entertainment"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["genre", "-score"], name="main_score_genre_8600f2_idx"
                    )
                ],
            },
        ),
    ]
